import Head from "next/head";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Functions from "@/components/Functions";

export default function Home() {
  return (
    <>
      <Head>
        <title>TypeBot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
        <Navbar></Navbar>
        <Hero></Hero>
        <Functions></Functions>
    </>
  );
}
